config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  resources :lists do
    resources :bookmarks, only: [:new, :create, :delete] do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :overview, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render:new
    end
  end

  def delete
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    # @movie = Movie.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render:new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render:new
    end
  end

  def destroy
    @list = Movie.find(params[:id])
    @list.delete
    redirect_to lists_path
  end

private

  def list_params
    params.require(:list).permit(:name, :movies)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render:new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render:new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.delete
    redirect_to movies_path
  end

private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<h2>Add a movie in <%= @list.name %></h2>
<%= simple_form_for [ @list, @bookmark ]  do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h2>Edit a List</h2>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>My list of lists</h1>
<div class="cards texte-white"><% @lists.each do |list| %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
<%= link_to list.name, list_path(list) %></div>
<% end %></div>

<%= link_to "Create a list", new_list_path, class: "btn btn-ghost" %>

app/views/lists/new.html.erb
<h2>Create a list</h2>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url();">
  <div class="container text-white">
    <h1><%= @list.name %></h1>
    <%= link_to "Update", edit_list_path(params[:id]), class: "btn btn-gradient" %>
    <%= link_to "Delete",
                  list_path(params[:id]),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-gradient" %>
    <%= link_to "Back to list", lists_path, class: "btn btn-flat" %>
    <%= link_to "Create a bookmark", new_list_bookmark_path(@list), class: "btn btn-flat" %>
  </div>
</div>

<div class="cards">
<% if @list %>
  <% @list.movies.each do |movie| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
    <%= link_to movie.title, movie_path(movie) %></div>
  <% end %></div>
<% end %>

app/views/movies/edit.html.erb
<h2>Edit a movie</h2>
<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1>My list of films</h1>
<div class="cards"><% @movies.each do |movie| %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.poster_url %>)">
<%= link_to movie.title, movie_path(movie) %></div>
<% end %></div>

<%= link_to "Create a movie", new_movie_path, class: "btn btn-ghost" %>

app/views/movies/new.html.erb
<h2>Create a movie</h2>
<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @movie.poster_url %>);">
  <div class="container">
    <h1><%= @movie.title %></h1>
    <p><%= @movie.overview %></p>
    <p><%= "⭐" * @movie.rating %></p>
    <%= link_to "Update", edit_movie_path(params[:id]), class: "btn btn-gradient" %>
    <%= link_to "Delete",
                  movie_path(params[:id]),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-gradient" %>
    <%= link_to "Back to films", movies_path, class: "btn btn-flat" %>

  </div>
</div>